package com.yanfei.scaffolding.privilege.dao;

import com.yanfei.scaffolding.privilege.entity.TbPrivilegePermission;

public interface TbPrivilegePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int insert(TbPrivilegePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int insertSelective(TbPrivilegePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    TbPrivilegePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int updateByPrimaryKeySelective(TbPrivilegePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int updateByPrimaryKey(TbPrivilegePermission record);
}