package com.yanfei.scaffolding.privilege.dao;

import com.yanfei.scaffolding.privilege.entity.TbPrivilegeRole;

public interface TbPrivilegeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int insert(TbPrivilegeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int insertSelective(TbPrivilegeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    TbPrivilegeRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int updateByPrimaryKeySelective(TbPrivilegeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int updateByPrimaryKey(TbPrivilegeRole record);
}