package com.yanfei.scaffolding.privilege.dao;

import com.yanfei.scaffolding.privilege.entity.TbPrivilegeUser;

public interface TbPrivilegeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_user
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_user
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int insert(TbPrivilegeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_user
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int insertSelective(TbPrivilegeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_user
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    TbPrivilegeUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_user
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int updateByPrimaryKeySelective(TbPrivilegeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_user
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int updateByPrimaryKey(TbPrivilegeUser record);
}