package com.yanfei.scaffolding.privilege.dao;

import com.yanfei.scaffolding.privilege.entity.TbPrivilegeRolePermission;

public interface TbPrivilegeRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int insert(TbPrivilegeRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int insertSelective(TbPrivilegeRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    TbPrivilegeRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int updateByPrimaryKeySelective(TbPrivilegeRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_privilege_role_permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    int updateByPrimaryKey(TbPrivilegeRolePermission record);
}