package com.yanfei.scaffolding.privilege.entity;

public class TbPrivilegeUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_user_role.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_user_role.user_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_user_role.role_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_user_role.id
     *
     * @return the value of tb_privilege_user_role.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_user_role.id
     *
     * @param id the value for tb_privilege_user_role.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_user_role.user_id
     *
     * @return the value of tb_privilege_user_role.user_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_user_role.user_id
     *
     * @param userId the value for tb_privilege_user_role.user_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_user_role.role_id
     *
     * @return the value of tb_privilege_user_role.role_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_user_role.role_id
     *
     * @param roleId the value for tb_privilege_user_role.role_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}