package com.yanfei.scaffolding.privilege.entity;

public class TbPrivilegeRolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_role_permission.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_role_permission.role_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_role_permission.permission_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_role_permission.id
     *
     * @return the value of tb_privilege_role_permission.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_role_permission.id
     *
     * @param id the value for tb_privilege_role_permission.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_role_permission.role_id
     *
     * @return the value of tb_privilege_role_permission.role_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_role_permission.role_id
     *
     * @param roleId the value for tb_privilege_role_permission.role_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_role_permission.permission_id
     *
     * @return the value of tb_privilege_role_permission.permission_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_role_permission.permission_id
     *
     * @param permissionId the value for tb_privilege_role_permission.permission_id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}