package com.yanfei.scaffolding.privilege.entity;

public class TbPrivilegePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_permission.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_permission.name
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_permission.permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_permission.pid
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_permission.is_leaf
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Boolean isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_privilege_permission.priority
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_permission.id
     *
     * @return the value of tb_privilege_permission.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_permission.id
     *
     * @param id the value for tb_privilege_permission.id
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_permission.name
     *
     * @return the value of tb_privilege_permission.name
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_permission.name
     *
     * @param name the value for tb_privilege_permission.name
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_permission.permission
     *
     * @return the value of tb_privilege_permission.permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_permission.permission
     *
     * @param permission the value for tb_privilege_permission.permission
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_permission.pid
     *
     * @return the value of tb_privilege_permission.pid
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_permission.pid
     *
     * @param pid the value for tb_privilege_permission.pid
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_permission.is_leaf
     *
     * @return the value of tb_privilege_permission.is_leaf
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Boolean getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_permission.is_leaf
     *
     * @param isLeaf the value for tb_privilege_permission.is_leaf
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setIsLeaf(Boolean isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_privilege_permission.priority
     *
     * @return the value of tb_privilege_permission.priority
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_privilege_permission.priority
     *
     * @param priority the value for tb_privilege_permission.priority
     *
     * @mbggenerated Wed Jun 20 16:32:29 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}